package sec

import (
	"time"
)

const (
	// DateFormat is the format used for date strings
	DateFormat = "2006-01-02"

	// AmendsSuffix is the suffix for amended filings
	AmendsSuffix = "/A"

	// SECRequestsPerSecMax is the maximum number of requests per second allowed by SEC
	SECRequestsPerSecMax = 10

	// HostWWWSEC is the main SEC website host
	HostWWWSEC = "www.sec.gov"

	// HostDataSEC is the SEC data API host
	HostDataSEC = "data.sec.gov"

	// URLCIKMapping is the URL for the CIK mapping file
	URLCIKMapping = "https://www.sec.gov/files/company_tickers_exchange.json"

	// URLFiling is the URL template for filing documents
	URLFiling = "https://www.sec.gov/Archives/edgar/data/%s/%s/%s"

	// URLFilingArchive is the URL template for the complete filing submission
	URLFilingArchive = "https://www.sec.gov/Archives/edgar/data/%s/%s/%s-index.html"

	// URLSubmissions is the URL template for submissions
	URLSubmissions = "https://data.sec.gov/submissions/%s"

	// SubmissionFileFormat is the format for submission files
	SubmissionFileFormat = "CIK%s.json"

	// RootSaveFolderName is the name of the root folder for saved filings
	RootSaveFolderName = "sec-edgar-filings"

	// FilingFullSubmissionFilename is the filename for full submissions
	FilingFullSubmissionFilename = "index.html"

	// PrimaryDocFilenameStem is the stem for primary document filenames
	PrimaryDocFilenameStem = "primary-document"

	// CIKLength is the length of a CIK
	CIKLength = 10
)

// DefaultBeforeDate is the default date before which to download filings (today)
var DefaultBeforeDate = time.Now()

// DefaultAfterDate is the default date after which to download filings (1994-01-01)
var DefaultAfterDate = time.Date(1994, 1, 1, 0, 0, 0, 0, time.UTC)

// SupportedForms is a map of supported SEC form types
var SupportedForms = map[string]bool{
	"1":                true,
	"1-A":              true,
	"1-A POS":          true,
	"1-A-W":            true,
	"1-E":              true,
	"1-E AD":           true,
	"1-K":              true,
	"1-SA":             true,
	"1-U":              true,
	"1-Z":              true,
	"1-Z-W":            true,
	"10-12B":           true,
	"10-12G":           true,
	"10-D":             true,
	"10-K":             true,
	"10-KT":            true,
	"10-Q":             true,
	"10-QT":            true,
	"11-K":             true,
	"13F":              true,
	"13F-HR":           true,
	"13F-NT":           true,
	"13H":              true,
	"144":              true,
	"15-12B":           true,
	"15-12G":           true,
	"15-15D":           true,
	"15F-12B":          true,
	"15F-12G":          true,
	"15F-15D":          true,
	"18-12B":           true,
	"18-12G":           true,
	"18-K":             true,
	"19B-4E":           true,
	"2-E":              true,
	"20-F":             true,
	"24F-2NT":          true,
	"25":               true,
	"25-NSE":           true,
	"3":                true,
	"4":                true,
	"40-17F1":          true,
	"40-17F2":          true,
	"40-17G":           true,
	"40-17GCS":         true,
	"40-24B2":          true,
	"40-33":            true,
	"40-8B25":          true,
	"40-8F-2":          true,
	"40-APP":           true,
	"40-F":             true,
	"40-OIP":           true,
	"424A":             true,
	"424B1":            true,
	"424B2":            true,
	"424B3":            true,
	"424B4":            true,
	"424B5":            true,
	"424B7":            true,
	"424B8":            true,
	"424H":             true,
	"425":              true,
	"485APOS":          true,
	"485BPOS":          true,
	"485BXT":           true,
	"486APOS":          true,
	"486BPOS":          true,
	"486BXT":           true,
	"487":              true,
	"497":              true,
	"497AD":            true,
	"497H2":            true,
	"497J":             true,
	"497K":             true,
	"5":                true,
	"6-K":              true,
	"8-A12B":           true,
	"8-A12G":           true,
	"8-K":              true,
	"8-K12B":           true,
	"8-K12G3":          true,
	"8-K15D5":          true,
	"8-M":              true,
	"9-M":              true,
	"ABS-15G":          true,
	"ABS-EE":           true,
	"ADV-E":            true,
	"ADV-H-C":          true,
	"ADV-H-T":          true,
	"ADV-NR":           true,
	"ATS-N":            true,
	"ATS-N-C":          true,
	"AW":               true,
	"C":                true,
	"C-AR":             true,
	"C-TR":             true,
	"C-U":              true,
	"C-W":              true,
	"CB":               true,
	"CERT":             true,
	"CFPORTAL":         true,
	"CT ORDER":         true,
	"D":                true,
	"DEF 14A":          true,
	"DEF 14C":          true,
	"DEFA14A":          true,
	"DEFC14A":          true,
	"DEFM14A":          true,
	"DEFN14A":          true,
	"DEFR14A":          true,
	"DEFR14C":          true,
	"DEL AM":           true,
	"DFAN14A":          true,
	"DFRN14A":          true,
	"DOS":              true,
	"DOSLTR":           true,
	"DRS":              true,
	"DRSLTR":           true,
	"DSTRBRPT":         true,
	"F-1":              true,
	"F-10":             true,
	"F-10EF":           true,
	"F-10POS":          true,
	"F-1MEF":           true,
	"F-3":              true,
	"F-3ASR":           true,
	"F-3D":             true,
	"F-3DPOS":          true,
	"F-3MEF":           true,
	"F-4":              true,
	"F-4 POS":          true,
	"F-4EF":            true,
	"F-4MEF":           true,
	"F-6":              true,
	"F-6 POS":          true,
	"F-6EF":            true,
	"F-7":              true,
	"F-7 POS":          true,
	"F-8":              true,
	"F-8 POS":          true,
	"F-80":             true,
	"F-80POS":          true,
	"F-9":              true,
	"F-9 POS":          true,
	"F-9EF":            true,
	"F-N":              true,
	"F-X":              true,
	"FOCUSN":           true,
	"FWP":              true,
	"G-405":            true,
	"G-FIN":            true,
	"G-FINW":           true,
	"IRANNOTICE":       true,
	"MA":               true,
	"MA-A":             true,
	"MA-I":             true,
	"MA-W":             true,
	"N-14":             true,
	"N-14 8C":          true,
	"N-14AE":           true,
	"N-14MEF":          true,
	"N-18F1":           true,
	"N-1A":             true,
	"N-2":              true,
	"N-23C-2":          true,
	"N-23C3A":          true,
	"N-23C3B":          true,
	"N-23C3C":          true,
	"N-2ASR":           true,
	"N-2MEF":           true,
	"N-30B-2":          true,
	"N-30D":            true,
	"N-4":              true,
	"N-5":              true,
	"N-54A":            true,
	"N-54C":            true,
	"N-6":              true,
	"N-6F":             true,
	"N-8A":             true,
	"N-8B-2":           true,
	"N-8F":             true,
	"N-8F NTC":         true,
	"N-CEN":            true,
	"N-CR":             true,
	"N-CSR":            true,
	"N-CSRS":           true,
	"N-MFP":            true,
	"N-MFP1":           true,
	"N-MFP2":           true,
	"N-PX":             true,
	"N-Q":              true,
	"N-VP":             true,
	"NPORT-EX":         true,
	"NPORT-NP":         true,
	"NPORT-P":          true,
	"NRSRO-UPD":        true,
	"NSAR-A":           true,
	"NSAR-AT":          true,
	"NSAR-B":           true,
	"NSAR-BT":          true,
	"NSAR-U":           true,
	"NT 10-D":          true,
	"NT 10-K":          true,
	"NT 10-Q":          true,
	"NT 11-K":          true,
	"NT 20-F":          true,
	"NT N-CEN":         true,
	"NT N-MFP":         true,
	"NT N-MFP1":        true,
	"NT N-MFP2":        true,
	"NT NPORT-EX":      true,
	"NT NPORT-P":       true,
	"NT NSAR":          true,
	"NT-NCEN":          true,
	"NT-NCSR":          true,
	"NT-NSAR":          true,
	"POS 8C":           true,
	"POS AM":           true,
	"POS AMI":          true,
	"POS EX":           true,
	"POS462B":          true,
	"POS462C":          true,
	"POSASR":           true,
	"PRE 14A":          true,
	"PRE 14C":          true,
	"PREC14A":          true,
	"PREC14C":          true,
	"PREM14A":          true,
	"PREM14C":          true,
	"PREN14A":          true,
	"PRER14A":          true,
	"PRER14C":          true,
	"PRRN14A":          true,
	"PX14A6G":          true,
	"PX14A6N":          true,
	"QRTLYRPT":         true,
	"QUALIF":           true,
	"REG-NR":           true,
	"REVOKED":          true,
	"RW":               true,
	"RW WD":            true,
	"S-1":              true,
	"S-11":             true,
	"S-11MEF":          true,
	"S-1MEF":           true,
	"S-20":             true,
	"S-3":              true,
	"S-3ASR":           true,
	"S-3D":             true,
	"S-3DPOS":          true,
	"S-3MEF":           true,
	"S-4":              true,
	"S-4 POS":          true,
	"S-4EF":            true,
	"S-4MEF":           true,
	"S-6":              true,
	"S-8":              true,
	"S-8 POS":          true,
	"S-B":              true,
	"S-BMEF":           true,
	"SC 13D":           true,
	"SC 13E1":          true,
	"SC 13E3":          true,
	"SC 13G":           true,
	"SC 14D9":          true,
	"SC 14F1":          true,
	"SC 14N":           true,
	"SC TO-C":          true,
	"SC TO-I":          true,
	"SC TO-T":          true,
	"SC13E4F":          true,
	"SC14D1F":          true,
	"SC14D9C":          true,
	"SC14D9F":          true,
	"SD":               true,
	"SDR":              true,
	"SE":               true,
	"SEC STAFF ACTION": true,
	"SL":               true,
	"SP 15D2":          true,
	"SUPPL":            true,
	"T-3":              true,
	"TA-1":             true,
	"TA-2":             true,
	"TA-A":             true,
	"TA-W":             true,
	"TACO":             true,
	"TH":               true,
	"TTW":              true,
	"UNDER":            true,
	"X-17A-5":          true,
}
